version: '2.4'
services:
  schedule-svc-svc:
    image: "servantscode/schedule-svc:latest"
    ports:
     - "84:8080"
    mem_limit: 128m
    environment:
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"
     
networks:
  default:
    external:
      name: docker-elk_elk
